### ISSUE TITLE
Missing content in README

### ISSUE THREAD

**Issue by KrisTarling** [jnmorse/react-webpack#12]
There's two things I've noticed missing in the README.md for this repo

1. The Contributor's Guide link is missing /.github/ and so returns a 404
2. There's a minor step missing in the installer guide which could cause some confusion:

```sh
git clone https://github.com/jnmorse/react-webpack.git
cd react-webpack   <----- this one here
npm install
cp sample.env .env
npm run serve
```

With your permission, I'll make these tweaks.

**Comment by jnmorse** [comment]
Fixed in #13
