### ISSUE TITLE
Cheatsheets additions

### ISSUE THREAD

**Issue by mtancoigne** [jnmorse/react-webpack#8]
I find two interesting cheatsheets :
  - http://ricostacruz.com/cheatsheets/react.html
  -  http://reactcheatsheet.com/

(Oh, and I forked the project, but the wiki did not came along, so i'll post suggestions/contributions here)

**Comment by jnmorse** [comment]
@mtancoigne the repo for the wiki itself is located here https://github.com/jnmorse/react-wiki

**Comment by jnmorse** [comment]
Thank you for opening the issue @mtancoigne.  However after reviewing these two links, I do not believe they are all that useful.

The first link mainly just contains the same information that can be found in the official React documentation.  It also references mixins which are deprecated.

The second link again just reiterates information, not even as completely as the official documentation.

I don't feel that I can suggest either of this is good resources as I don't feel like either provide any useful information for working with React.

If you find any other resources that you think should be included or what to contribute anything to the wiki please feel free to do so in the repo mentioned in the previous comment.

Also thank you for trying to promote the wiki! :smile:  I've been hesitant to do so.
